<?php
$this->title = 'Add new album';
$this->headTitle($this->title);
?>

<form action="<?= $this->url(array('action'=>'add')); ?>" method="post">
    <div class="form-group">
        <label for="artist">Artist</label>
        <input type="text" class="form-control" name="artist" required>
    </div>
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" name="title" required>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>